### ISSUE TITLE
Déploiement API : TODO

### ISSUE THREAD

**Issue by avouacr** [InseeFrLab/llm-open-data-insee#12]
- [ ] API
  - [x] Version basique synchrone
  - [x] Cache S3 des modèles ?
  - [ ] Implémenter le streaming

- [ ] Déploiement
  - [x] Dockerfile
  - [x] CI
  - [x] Contrats Kubernetes
  - [ ] CD
  - [ ] Faire un dépôt dédié
