### ISSUE TITLE
Tracking des expérimentations : logging

### ISSUE THREAD

**Issue by ThomasFaria** [InseeFrLab/llm-open-data-insee#14]
Petite discussion pour se mettre d'accord sur quoi logger à chaque expérimentation exécutée via [run_pipeline.py](https://github.com/InseeFrLab/llm-open-data-insee/blob/main/src/run_pipeline.py).

Pour le moment on log :

- Hyper paramètres: 
  - [x] le path s3 de la chroma DB
  - [x] Nom modèle LLM
  - [x] Nom modèle d'embedding
  - [x] Template de prompt
 

- Métriques :

  - [ ]  ?

- Artifacts : 

  - [ ] Réponse du modèle
  - [ ] Documents récupérés
  - [ ] Métadata récupérés

## Dans la constitution de la base de données vectorielles

- Hyper paramètres: 
  - [x] le path s3 de la chroma DB
  - [x] Nom modèle d'embedding
  - [ ] Nombre de pages utilisées pour construire la database
  - [ ] chunk_size
  - [ ] chunk_overlap
  

- Métriques : 

- [ ] Nombre de documents

- Artifacts:

  - [x] Exemples de documents
  - [x] Environnement: code python, requirements
